### PR TITLE
Added constraintPassed() functionality.

### PR DESCRIPTION
**Pull request by VidyashreeBL**
constraintPassed methoid checks if a given string matches with the regular expression stored in the variable regExpression.

### CODE REVIEW

**Comment by anubhavchaturvedi** [comment]
@manishengi , @shikha151 : can we test this?

**Comment by manishengi** [comment]
We are looking at it.

**Comment by anubhavchaturvedi** [comment]
@VidyashreeBL : make sure you test if the build is passing before merging.

**Comment by VidyashreeBL** [comment]
ok, got it. Rubeena implemented the same functionality, you can leave my changes.

**Pull request merged**
